field: 64286a3d-abda-4015-acb6-fdd84a52c3e7 # Content Blocks
fieldLayouts:
  478f9681-32e0-4ead-b281-724b8f9e992d:
    tabs:
      -
        elements:
          -
            fieldUid: de1e22e5-fa6c-4c7d-bbb2-d4d62a99fc0f # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 13e32631-20b2-4c89-9eb0-8e08086c0732 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  13e32631-20b2-4c89-9eb0-8e08086c0732: # Copy
    columnSuffix: bloablfu
    contentColumnType: text
    fieldGroup: null
    handle: copy
    instructions: ''
    name: Copy
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  de1e22e5-fa6c-4c7d-bbb2-d4d62a99fc0f: # Headline
    columnSuffix: vzvdurwx
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: form
name: Form
sortOrder: 5
