field: 64286a3d-abda-4015-acb6-fdd84a52c3e7 # Content Blocks
fieldLayouts:
  fb664e1b-c756-4ff5-bff5-7fe15fd0ac4a:
    tabs:
      -
        elements:
          -
            fieldUid: 2ec7c7ab-443a-47cd-ae26-923a25339dc1 # Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 28c471b6-f9c0-47ae-b77c-d6f2d1b46442 # Copy
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 26a2f3c6-7268-458a-8fa1-dd9f185d5cdf # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  2ec7c7ab-443a-47cd-ae26-923a25339dc1: # Headline
    columnSuffix: ldeoqtnq
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  26a2f3c6-7268-458a-8fa1-dd9f185d5cdf: # Buttons
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: buttons
    instructions: ''
    name: Buttons
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 3e6a5880-c066-46c5-a8c1-b94edd8a3a28 # Button
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_5_buttons}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationKeyFormat: null
      propagationMethod: all
      selectionLabel: 'Add a button'
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  28c471b6-f9c0-47ae-b77c-d6f2d1b46442: # Copy
    columnSuffix: rndbqxmv
    contentColumnType: text
    fieldGroup: null
    handle: copy
    instructions: ''
    name: Copy
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: ''
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showHtmlButtonForNonAdmins: ''
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: enlarged
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: hero
name: Hero
sortOrder: 6
