fieldLayouts:
  5d8d99f5-8168-492c-b05d-95964f303475:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: cloudFiles
hasUrls: true
name: 'Cloud Files'
settings:
  addSubfolderToRootUrl: '1'
  autoFocalPoint: ''
  bucket: $AWS_BUCKET
  bucketSelectionMode: manual
  cfDistributionId: $AWS_CLOUDFRONT_ID
  cfPrefix: $AWS_CLOUDFRONT_PREFIX
  expires: ''
  keyId: $AWS_ACCESS_KEY_ID
  makeUploadsPublic: ''
  region: $AWS_REGION
  secret: $AWS_SECRET_ACCESS_KEY
  storageClass: ''
  subfolder: ''
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: craft\awss3\Volume
url: $AWS_CLOUDFRONT_URL
